BINNAME := genmap
BINEXT := so

# directories
SRCDIR := src
BINDIR := ../bin/linux
OBJDIR := ../temp/linux/$(BINNAME)
DEPDIR := ../temp/linux/$(BINNAME)

CFLAGS := -std=c11
CXXFLAGS := -std=c++17
CPPFLAGS := -Wall -Wextra -fPIC
LDFLAGS := -shared
LDLIBS :=

CC := gcc
CXX := g++
LD := $(CXX)

include ../Makefile.in